version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: NkYVaAoS46Mm13sE
    ports:
      - 27017:27017
    volumes:
      - ./data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: sogo
      ME_CONFIG_BASICAUTH_PASSWORD: sogo29
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: NkYVaAoS46Mm13sE
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: always


