version: '3.8'

services:

  reader:
    image: sogo/reader
    container_name: reader
    ports:
      - "8080:8080"
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - host

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: NkYVaAoS46Mm13sE
    ports:
      - "27017:27017"
    volumes:
      - ./database-data:/data/db
    restart: always
    networks:
      - host

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: sogo
      ME_CONFIG_BASICAUTH_PASSWORD: sogo29
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: NkYVaAoS46Mm13sE
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: always
    networks:
      - host

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus:/etc/prometheus
    networks:
      - host
    links:
      - reader
    depends_on:
      - reader

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_PROTOCOL: http
      GF_SERVER_HTTP: 3000
    networks:
      - host
    links:
      - prometheus
    depends_on:
      - prometheus

networks:
  host:


