global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
 
  - job_name: 'reader'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'reader:8080' ]